/*
 * Compile `personalities/<slug>/brief.yml` into `src/generated/personas.ts`.
 *
 * Why generate a TS module rather than read the YAML at runtime: a handler that calls `readFileSync`
 * needs a filesystem, which means declaring `host: docker` and giving up the lighter execution host
 * for one string. Baking the brief into the bundle at build time keeps the handler pure, and keeps
 * the single source of truth in the place a persona is authored — an operator reads `brief.yml`, and
 * the generated file is never hand-edited.
 *
 * Run by `npm run build` before tsc. Deliberately tiny: YAML parsing here is the two block-scalar
 * fields the brief actually uses, because adding a yaml dependency to a realm whose whole build is
 * `tsc` is a worse trade than thirty lines of reader. If brief.yml ever needs real YAML, take the
 * dependency then rather than growing this.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import * as path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const personalities = path.join(root, "personalities");
const outDir = path.join(root, "src", "generated");

/**
 * Read the scalar and block-scalar top-level fields of a brief. Returns strings only; nested
 * structure (`sampling`, `notebook`) is the HOST's to read from the YAML, not the handler's.
 */
function readBrief(file) {
  const lines = readFileSync(file, "utf8").split("\n");
  const out = {};
  let key = null;
  let buf = [];
  const flush = () => {
    if (key) out[key] = buf.join("\n").replace(/\s+$/, "");
    key = null;
    buf = [];
  };
  for (const line of lines) {
    /* A top-level key: no leading space, a name, a colon. */
    const top = /^([A-Za-z][A-Za-z0-9_]*):(.*)$/.exec(line);
    if (top) {
      flush();
      const name = top[1];
      const rest = top[2].trim();
      if (rest === "|" || rest === ">-" || rest === ">" || rest === "|-") {
        key = name;
      } else if (rest && !rest.startsWith("#")) {
        /* An inline scalar, quoted or bare. */
        out[name] = rest.replace(/^["']|["']$/g, "");
      }
      continue;
    }
    if (key) {
      if (line.trim() === "" || /^\s{2,}/.test(line)) buf.push(line.replace(/^ {2}/, ""));
      else flush();
    }
  }
  flush();
  return out;
}

const slugs = existsSync(personalities)
  ? readdirSync(personalities, { withFileTypes: true })
      .filter((d) => d.isDirectory())
      .map((d) => d.name)
      .sort()
  : [];

const personas = [];
for (const slug of slugs) {
  const briefFile = path.join(personalities, slug, "brief.yml");
  const identityFile = path.join(personalities, slug, "identity.yml");
  if (!existsSync(briefFile)) continue; /* chat-only persona: not offered to a verb */
  const brief = readBrief(briefFile);
  const identity = existsSync(identityFile) ? readBrief(identityFile) : {};
  personas.push({
    slug,
    name: identity.name || slug,
    tagline: identity.description || "",
    brief: brief.brief || "",
    objective: brief.objective || null,
    openingMove: brief.openingMove || null,
  });
}

if (!personas.length) throw new Error("No persona has a brief.yml — askMaestro would have no voice.");

const banner = `/*
 * GENERATED by scripts/personas.mjs from personalities/<slug>/brief.yml. Do not edit.
 *
 * The personas a realm verb can speak as. Authoring lives in the YAML; this is the compiled form so
 * the handler needs no filesystem at runtime. Run \`npm run build\` after changing a brief.
 */`;

writeFileSync(
  path.join((mkdirSync(outDir, { recursive: true }), outDir), "personas.ts"),
  `${banner}

export interface PersonaBrief {
  slug: string;
  name: string;
  tagline: string;
  /** The persona compacted for one request. */
  brief: string;
  /** What it is trying to achieve. A persona with one advocates; withheld once asked to stop. */
  objective: string | null;
  openingMove: string | null;
}

export const PERSONAS: PersonaBrief[] = ${JSON.stringify(personas, null, 2)};

/** One persona by slug, or undefined — a caller naming an unknown guide gets told, not guessed at. */
export const personaBySlug = (slug: string): PersonaBrief | undefined =>
  PERSONAS.find((p) => p.slug === (slug || "").trim().toLowerCase());

/** Every slug this realm ships, for an error message that lists the real options. */
export const personaSlugs = (): string[] => PERSONAS.map((p) => p.slug);
`,
);

process.stdout.write(`personas: ${personas.map((p) => p.slug).join(", ")}\n`);
